IGL.UI/Controllers/Inventory/PurchaseOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IGL.Core.Comman.Helper;
using IGL.Core.Entities.Inventory;
using IGL.Core.Entities.Master;
using IGL.Core.Service.GenericService;
using IGL.Core.Service.PurchaseOrder;
using IGL.Core.ViewModelEntities.Inventory;
using IGL.Core.ViewModelEntities.MasterVm;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace IGL.UI.Controllers.Inventory
{
    public class PurchaseOrderController : Controller
    {
        private readonly IGenericService<PurchaseOrder, int> _IPurchaseOrderService;
        private readonly IGenericService<POItem, int> _IPOItemService;
        private readonly IGenericService<VendorMaster, int> _IVendorService;
        private readonly IGenericService<MaterialMaster, int> _IProductService;
        private readonly IGenericService<UnitMaster, int> _IunitMasterService;
        private readonly IGenericService<IGL.Core.Entities.Organization.Organisation, int> _IOrganisationService;
        private readonly IPurchaseOrderService _IPurchaseOrder;

        public PurchaseOrderController(IGenericService<PurchaseOrder, int> purchaseOrderService, 
            IGenericService<POItem, int> poItemService, IGenericService<VendorMaster, int> vendorService, 
            IGenericService<MaterialMaster, int> productService, IGenericService<UnitMaster, int> unitMasterService, 
            IGenericService<IGL.Core.Entities.Organization.Organisation, int> organisationService, IPurchaseOrderService purchaseOrder)
        {
            _IPOItemService = poItemService;
            _IPurchaseOrderService = purchaseOrderService;
            _IVendorService = vendorService;
            _IProductService = productService;
            _IunitMasterService = unitMasterService;
            _IOrganisationService = organisationService;
            _IPurchaseOrder = purchaseOrder;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.PoStatusCount = await _IPurchaseOrder.GetPoStatusCount();
            return View("~/Views/PurchaseOrder/POIndex.cshtml");
        }

        public async Task<IActionResult> CreatePO()
        {
            string poNumber = "PO00" + Convert.ToString(1);
            var poDetails = await _IPurchaseOrderService.GetList(x => x.IsActive == 1);
            if(poDetails.Count()>0)
            {
                poNumber = poNumber + (poDetails.Max(x => x.Id)+1).ToString();
            }
            ViewData["poNumber"] = poNumber;
            var vendorDetails = await _IVendorService.GetList(x => x.IsActive == 1);
            ViewBag.VendorList = vendorDetails;
            return await Task.Run(() => PartialView("~/Views/PurchaseOrder/_CreatePurchaseOrderPartial.cshtml"));
        }

        public async Task<IActionResult> GetPOList(int poStatus)
        {
            /*
             po Status -1 for Po Created
             po status -2 for Approved
             po status -3 for siv created
             po status -4 for siv approved
             */

            var poDetail = await _IPurchaseOrderService.GetList(x => x.IsActive == 1);
            var poItems = await _IPOItemService.GetList(x => x.IsActive == 1);
            var vendorDetails = await _IVendorService.GetList(x => x.IsActive == 1);
            var productDetails = await _IProductService.GetList(x => x.IsActive == 1);

            switch (poStatus)
            {
                case 1:
                    poDetail = poDetail.Where(x => x.POStatus.Trim().ToLower() == "created").ToList();
                    ViewBag.poStatus = "created";
                    break;

                case 2:
                    poDetail = poDetail.Where(x => x.POStatus.Trim().ToLower() == "poapproved").ToList();
                    ViewBag.poStatus = "poapproved";
                    break;

                case 3:
                    poDetail = poDetail.Where(x => x.POStatus.Trim().ToLower() == "sivcreated").ToList();
                    ViewBag.poStatus = "sivcreated";
                    break;

                case 4:
                    poDetail = poDetail.Where(x => x.POStatus.Trim().ToLower() == "sivapproved").ToList();
                    ViewBag.poStatus = "sivapproved";
                    break;

                default:
                    break;
            }



            var models = (from PO in poDetail
                          join VM in vendorDetails
                          on PO.VendorId equals VM.Id
                          join PI in poItems
                          on PO.Id equals PI.PoId
                          join PRD in productDetails
                          on PI.ItemId equals PRD.Id
                          select new PurchaseOrderDetail
                          {
                              PoId = PO.Id,
                              PoNUmber = PO.PONumber,
                              PoDate = PO.PODate,
                              VendorName = VM.VendorName,
                              ItemId = PI.ItemId,
                              ItemName = PRD.Name,
                              Quantity = PI.Quantity,
                              UnitPrice = PRD.PerUnitCost,
                              Amount = PI.Quantity * PRD.PerUnitCost,
                              Remarks = PO.Remarks,
                              POStatus = PO.POStatus
                          }).ToList();

            return PartialView("~/Views/PurchaseOrder/_PurchaseOrderDetails.cshtml", models);

        }

        public async Task<IActionResult> MaterialForPo()
        {
            var unitModels = await _IunitMasterService.GetList(x => x.IsActive == 1);
            var materialModels = await _IProductService.GetList(x => x.IsActive == 1 && x.IsUnique==0);


            var models = (from mt in materialModels
                          join UM in unitModels
                          on mt.UnitId equals UM.Id
                          select new MaterialMasterVm
                          {
                              Id = mt.Id,
                              MaterialName = mt.Name,
                              Code = mt.Code,
                              Unit = UM.Name,
                              PerUnitCost = mt.PerUnitCost,
                              IsPayable = mt.IsPayable == 1 ? "Payable" : "Free (IGL Product)"
                          }).ToList();
            return PartialView("~/Views/PurchaseOrder/_AddMaterialToPOPartial.cshtml", models);
        }

        public async Task<IActionResult> CreatePurchaseOrder(PurchaseOrder model, string[] matId, string[] remarks, string[] qty, string[] unitPrice, int poId)
        {
            //if po already exists then Approve the po
            if ((await _IPurchaseOrderService.GetList(x => x.IsActive == 1 && x.Id== poId)).Count() > 0)
            {
                var poDetail = await _IPurchaseOrderService.GetSingle(x => x.Id == poId);
                poDetail.POStatus = "POApproved";
                await _IPurchaseOrderService.Update(poDetail);
                var poItems = await _IPOItemService.GetList(x => x.PoId == poDetail.Id);

                poItems.ToList().ForEach(item => {
                    item.IsActive = 0;
                    item.IsDeleted = 1;
                    item.UpdatedBy = 1;
                    item.UpdatedDate = DateTime.Now.Date;
                });
                var deletePreviousPoItems = await _IPOItemService.Update(poItems.ToArray());

                List<POItem> tempPOItems = new List<POItem>();

                for (int i = 0; i < matId.Count(); i++)
                {
                    POItem item = new POItem();
                    item.PoId = poDetail.Id;
                    item.ItemId = Convert.ToInt32(matId[i]);
                    item.Quantity = Convert.ToInt32(qty[i]);
                    item.Amount = Convert.ToDecimal(Convert.ToInt32(qty[i]) * Convert.ToDecimal(unitPrice[i]));
                    item.Remarks = remarks[i];
                    item.IsActive = 1;
                    item.IsDeleted = 0;
                    item.CreatedBy = 1;
                    item.CreatedDate = DateTime.Now.Date;
                    tempPOItems.Add(item);
                }

                var itemResponse = await _IPOItemService.Add(tempPOItems.ToArray());
                return Json(ResponseHelper.GetResponseMessage(itemResponse));
            }
            else
            { 
                var createHelper = CommanCRUDHelper.CommanCreateCode(model, 1);
                createHelper.POStatus = "Created";
                var response = await _IPurchaseOrderService.CreateEntity(model);
                var tempPoId = (await _IPurchaseOrderService.GetList(x => x.IsActive == 1)).Max(x => x.Id);

                List<POItem> poItems = new List<POItem>();

                for (int i = 0; i < matId.Count(); i++)
                {
                    POItem item = new POItem();
                    item.PoId = tempPoId;
                    item.ItemId = Convert.ToInt32(matId[i]);
                    item.Quantity = Convert.ToInt32(qty[i]);
                    item.Amount = Convert.ToDecimal(Convert.ToInt32(qty[i]) * Convert.ToDecimal(unitPrice[i]));
                    item.Remarks = remarks[i];
                    item.IsActive = 1;
                    item.IsDeleted = 0;
                    item.CreatedBy = 1;
                    item.CreatedDate = DateTime.Now.Date;
                    poItems.Add(item);
                }

                var itemResponse = await _IPOItemService.Add(poItems.ToArray());
                return Json(ResponseHelper.GetResponseMessage(itemResponse));
            }
           
            }

        public async Task<IActionResult> POPDF(int id)
        {
            List<PurchaseOrderDetail> models = await GetPoDetail(id);
            return PartialView("~/Views/PurchaseOrder/_POPDFPartial.cshtml", models);
        }

IGL.UI/Controllers/Inventory/VendorMasterController.cs
using System.Linq;
using System.Threading.Tasks;
using IGL.Core.Comman.Helper;
using IGL.Core.Entities.Inventory;
using IGL.Core.Service.GenericService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IGL.UI.Controllers.Inventory
{
    [Authorize]
    public class VendorMasterController : Controller
    {
        private readonly IGenericService<VendorMaster, int> _IVendorMasterService;

        public VendorMasterController(IGenericService<VendorMaster,int> _vendorMasterService)
        {
            _IVendorMasterService = _vendorMasterService;
        }
        public async Task<IActionResult>  Index()
        {
            return await Task.Run(()=> View("~/Views/Inventory/VendorIndex.cshtml"));
        }

        public async Task<IActionResult> GetVendorList(string vendorName)
        {
            var models = await _IVendorMasterService.GetList(x => x.IsActive == 1);
            return PartialView("~/Views/Inventory/_VendorListPartial.cshtml", models.OrderByDescending(x => x.Id).ThenBy(x => x.UpdatedDate).ToList());
        }

        public async Task<IActionResult> CreateVendor(int id)
        {
            var model = await _IVendorMasterService.GetSingle(x => x.Id == id);
            return PartialView("~/Views/Inventory/_CreateVendorPartial.cshtml", model);
        }
        [HttpPost]
        public async Task<IActionResult> UpSertVendor(VendorMaster model)
        {
            if(model.Id==0)
            {
                var createModel = CommanCRUDHelper.CommanCreateCode(model, 1);
                var response = await _IVendorMasterService.CreateEntity(createModel);
                return Json(ResponseHelper.GetResponseMessage(response));
            }

            var updateModel = CommanCRUDHelper.CommanUpdateCode(model, 1);
            var updateRespose = await _IVendorMasterService.Update(updateModel);
            return Json(ResponseHelper.GetResponseMessage(updateRespose));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _IVendorMasterService.GetSingle(x => x.Id == id);
            var deleteModel = CommanCRUDHelper.CommanDeleteCode(model, 1);
            var response = await _IVendorMasterService.Update(deleteModel);
            return Json(ResponseHelper.GetResponseMessage(response));
        }
    }
}

IGL.UI/Views/Inventory/VendorIndex.cshtml
@{
    ViewData["Title"] = "Vendor Detail";
}

<section class="content-header">
    <h1>
        Vendor Detail
    </h1>
</section>
<section class="content container-fluid">
    <section class="content">
        <div class="row" id="divVendorIndex">
        </div>
    </section>
    @await Html.PartialAsync("~/Views/Shared/IGLCommanModal.cshtml")
</section>


<environment include="Production">
    <script src="~/js/Inventory/Vendor.js"></script>
</environment>
<environment include="Development">
    <script src="~/js/Inventory/Vendor.js"></script>
</environment>

IGL.UI/Views/Inventory/_CreateVendorPartial.cshtml
@model IGL.Core.Entities.Inventory.VendorMaster

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<form id="form" method="post" data-ajax="true" data-ajax-method="post"
      asp-action="UpSertVendor" asp-controller="VendorMaster" data-ajax-success="vendorDetail.Fn_Success"
      data-ajax-begin="customAjax.Fn_SubmitBegin(divModalPopUp)" data-ajax-complete="customAjax.Fn_SubmitComplete(divModalPopUp)">
    <div class="row">
        <div class="col-xs-12">
            <div class="col-md-4 form-group">
                <input type="hidden" asp-for="Id" />
                <label class="control-label"> Vendor Name</label>
                <input asp-for="VendorName" class="form-control" />
                <span asp-validation-for="VendorName"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Vendor Type</label>
                <select asp-for="VendorType" class="form-control">
                    <option value="Client">Client</option>
                    <option value="Direct Procurement">Direct Procurement</option>
                </select>
                <span asp-validation-for="VendorType"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Vendor Email</label>
                <input asp-for="VendorEmail" class="form-control" />
                <span asp-validation-for="VendorEmail"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">PAN Number</label>
                <input asp-for="PANNumber" class="form-control" />
                <span asp-validation-for="PANNumber"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">GST Number</label>
                <input asp-for="GSTNumber" class="form-control" />
                <span asp-validation-for="GSTNumber"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Address Line1</label>
                <input asp-for="AddressLine1" class="form-control" />
                <span asp-validation-for="AddressLine1"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Address Line 2</label>
                <input asp-for="AddressLine2" class="form-control" />
                <span asp-validation-for="AddressLine2"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Contact Person</label>
                <input asp-for="ContactPerson" class="form-control" />
                <span asp-validation-for="ContactPerson"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Contact Email</label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Contact Phone</label>
                <input asp-for="ContactPhone" class="form-control" />
                <span asp-validation-for="ContactPhone"></span>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="col-sm-8">
                <button type="submit" class="btn btn-primary pull-right" value="Save">
                    <i class="fa fa-download"> &nbsp;&nbsp;Save</i>
                </button>
            </div>
            <div class="col-sm-4">
                <button type="reset" class="btn btn-warning" value="reset">
                    <i class="fa fa-refresh">&nbsp;&nbsp;Reset</i>
                </button>
            </div>
        </div>
    </div>
</form>

IGL.UI/Views/Inventory/_VendorListPartial.cshtml
@model IEnumerable<IGL.Core.Entities.Inventory.VendorMaster>
@{
    ViewData["Title"] = "Vendor Detail";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Vendor Details</h3>

                <button class="btn btn-primary pull-right" onclick="vendorDetail.Fn_CreateVendor()">
                    <i class="fa fa-plus-circle"> &nbsp; &nbsp; Add &nbsp; &nbsp;</i>
                </button>

            </div>
            <div class="box-body">
                <table id="IGLDataTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th> Vendor Name</th>
                            <th>Vendor Type</th>
                            <th>Vendor Email</th>
                            <th>Vendor Phone</th>
                            <th>PAN</th>
                            <th>GST</th>
                            <th>Address Line 1</th>
                            <th>Address Line 2</th>
                            <th>Contact Person</th>
                            <th>Email(Contact Person)</th>
                            <th>Phone(Contact Person)</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var data in Model)
                        {
                            <tr>
                                <td>
                                    @data.VendorName
                                </td>
                                <td>
                                    @data.VendorType
                                </td>
                                <td>
                                    @data.VendorEmail
                                </td>
                                <td>
                                    @data.VendorPhone
                                </td>
                                <td>
                                    @data.PANNumber
                                </td>
                                <td>
                                    @data.GSTNumber
                                </td>
                                <td>
                                    @data.AddressLine2
                                </td>
                                <td>
                                    @data.AddressLine2
                                </td>
                                <td>
                                    @data.ContactPerson
                                </td>
                                <td>
                                    @data.ContactEmail
                                </td>
                                <td>
                                    @data.ContactPhone
                                </td>
                                <td>

                                    <a class="btn btn-outline-danger pull-right" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'  style='color:#DD4B39'></i>" onclick="vendorDetail.Fn_DeleteVendor(@data.Id, this)">
                                        <i class="fa fa-trash" style="color:#DD4B39"></i>
                                    </a>

                                    <a class="btn btn-outline-success pull-right" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'  style='color:#DD4B39'></i>" onclick="vendorDetail.Fn_EditVendor(@data.Id, this)">
                                        <i class="fa fa-edit" style="color:#3C8DBC"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>