IGL.UI/Controllers/Master/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IGL.Core.Comman.Helper;
using IGL.Core.Entities.Master;
using IGL.Core.Service.GenericService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IGL.UI.Controllers.Master
{
    [Authorize]
    public class CustomerController : Controller
    {
        private readonly IGenericService<CustomerMaster, int> _ICustomerMasterService;
        public CustomerController(IGenericService<CustomerMaster, int> _customerService)
        {
            _ICustomerMasterService = _customerService;
        }
        public async Task<IActionResult> Index()
        {
            return await Task.Run(() => View("~/Views/Master/CustomerMaster/CustomerIndex.cshtml"));
        }
        public async Task<IActionResult> CreateCustomer(int id)
        {   
            var model = await _ICustomerMasterService.GetSingle(x => x.Id == id);
            return PartialView("~/Views/Master/CustomerMaster/_customerCreatePartial.cshtml", model);
        }
        public async Task<IActionResult> GetCustomerList()
        {
            var models = await _ICustomerMasterService.GetList(x => x.IsActive == 1);
            return PartialView("~/Views/Master/CustomerMaster/_CustomerListPartial.cshtml", models.OrderByDescending(x => x.CreatedDate).ThenBy(x => x.UpdatedDate));
        }

        [HttpPost]
        public async Task<IActionResult> UpSertCustomer(CustomerMaster modelEntity)
        {
            if(modelEntity.Id==0)
            {
                var createHelperModel = CommanCRUDHelper.CommanCreateCode(modelEntity, 1);
                var createResponse = await _ICustomerMasterService.CreateEntity(createHelperModel);
                return Json(ResponseHelper.GetResponseMessage(createResponse));
            }
            var updateHelperModel = CommanCRUDHelper.CommanUpdateCode(modelEntity, 1);
            var updateResponse = await _ICustomerMasterService.Update(updateHelperModel);
            return Json(ResponseHelper.GetResponseMessage(updateResponse));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _ICustomerMasterService.GetSingle(x => x.Id == id);
            var deleteModel = CommanCRUDHelper.CommanDeleteCode(model, 1);
            await _ICustomerMasterService.CreateNewContext();
            var deleteResponse = await _ICustomerMasterService.Update(deleteModel);
            return Json(ResponseHelper.GetResponseMessage(deleteResponse));
        }
    }
}

IGL.UI/Controllers/Master/EmployeeDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IGL.Core.Comman.Helper;
using IGL.Core.Entities.Master;
using IGL.Core.Service.GenericService;
using IGL.Core.ViewModelEntities.MasterVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IGL.UI.Controllers.Master
{
    [Authorize]
    public class EmployeeDetailController : Controller
    {
        private readonly IGenericService<EmployeeDetail, int> _IEmployeeDetailService;
        private readonly IGenericService<EmployeeType, int> _IEmployeeTypeService;

        public EmployeeDetailController(IGenericService<EmployeeDetail, int> employeeDetailService, IGenericService<EmployeeType, int> employeeTypeService)
        {
            _IEmployeeDetailService = employeeDetailService;
            _IEmployeeTypeService = employeeTypeService;
        }
        public async Task<IActionResult> Index()
        {
            return await Task.Run(()=> View("~/Views/Master/Employee/EmployeeIndex.cshtml"));
        }

        public async Task<IActionResult> GetEmployeeDetails()
        {
            var employeeTypeDetails = await _IEmployeeTypeService.GetList(x => x.IsActive == 1);
            var employeeDetails = await _IEmployeeDetailService.GetList(x => x.IsActive == 1);

            var models = (from ED in employeeDetails
                          join ET in employeeTypeDetails
                          on ED.EmployeeTypeId equals ET.Id
                          select new EmployeeDetailVm
                          {
                              Id = ED.Id,
                              Name = ED.Name,
                              EmployeeType = ET.Name,
                              EmailId = ED.EmailId,
                              Phone = ED.Phone,
                              Address = ED.PanNo

                          }).ToList();
            return PartialView("~/Views/Master/Employee/_EmployeeListPartial.cshtml", models);
        }

        public async Task<IActionResult> UpsertEmployeeDetail(int id)
        {
            ViewBag.EmployeeType = await _IEmployeeTypeService.GetList(x => x.IsActive == 1);
            var model = await _IEmployeeDetailService.GetSingle(x => x.Id == id);
            return PartialView("~/Views/Master/Employee/_CreateEmployeePartial.cshtml", model);
        }


        [HttpPost]
        public async Task<IActionResult> UpSertEmployeeDetail(EmployeeDetail model)
        {
            if (model.Id > 0)
            {
                var updateModel = CommanCRUDHelper.CommanUpdateCode(model, 1);
                var updateResponse = await _IEmployeeDetailService.Update(updateModel);
                return Json(ResponseHelper.GetResponseMessage(updateResponse));
            }
            var createModel = CommanCRUDHelper.CommanCreateCode(model, 1);
            var createResponse = await _IEmployeeDetailService.CreateEntity(createModel);
            return Json(ResponseHelper.GetResponseMessage(createResponse));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _IEmployeeDetailService.GetSingle(x => x.Id == id);
            var deleteModel = CommanCRUDHelper.CommanDeleteCode(model, 1);
            await _IEmployeeDetailService.CreateNewContext();
            var response = await _IEmployeeDetailService.Update(deleteModel);
            return Json(ResponseHelper.GetResponseMessage(response));
        }

    }
}

IGL.UI/Controllers/Master/EmployeeTypeController.cs
using System.Threading.Tasks;
using IGL.Core.Comman.Helper;
using IGL.Core.Entities.Master;
using IGL.Core.Service.GenericService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IGL.UI.Controllers.Master
{
    [Authorize]
    public class EmployeeTypeController : Controller
    {
        private readonly IGenericService<EmployeeType, int> _IEmployeeTypeService;

        public EmployeeTypeController(IGenericService<EmployeeType, int> employeeTypeService)
        {
            _IEmployeeTypeService = employeeTypeService;
        }
        public async Task<IActionResult> Index()
        {
            return await Task.Run(()=> View("~/Views/Master/EmployeeType/EmployeeTypeIndex.cshtml"));
        }

        public async Task<IActionResult> GetEmployeeTypeDetails()
        {
            var models = await _IEmployeeTypeService.GetList(x => x.IsActive == 1);
            return PartialView("~/Views/Master/EmployeeType/_EmployeeTypeList.cshtml", models);

        }

        public async Task<IActionResult> UpSertEmployeeType(int id)
        {
            var model = await _IEmployeeTypeService.GetSingle(x => x.Id == id);
            return PartialView("~/Views/Master/EmployeeType/_EmployeeTypeCreate.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> UpSertEmployeeType(EmployeeType model)
        {
            if(model.Id>0)
            {
                var updateModel = CommanCRUDHelper.CommanUpdateCode(model, 1);
                var updateResponse = await _IEmployeeTypeService.Update(updateModel);
                return Json(ResponseHelper.GetResponseMessage(updateResponse));
            }
            var createModel = CommanCRUDHelper.CommanCreateCode(model, 1);
            var createResponse = await _IEmployeeTypeService.CreateEntity(createModel);
            return Json(ResponseHelper.GetResponseMessage(createResponse));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var model = await _IEmployeeTypeService.GetSingle(x => x.Id == id);
            var deleteModel = CommanCRUDHelper.CommanDeleteCode(model, 1);
            await _IEmployeeTypeService.CreateNewContext();
            var response = await _IEmployeeTypeService.Update(deleteModel);
            return Json(ResponseHelper.GetResponseMessage(response));
        }
    }
}

IGL.UI/Controllers/Master/MaterialMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IGL.Core.Comman.Helper;
using IGL.Core.Entities.Master;
using IGL.Core.Entities.ProductTransaction;
using IGL.Core.Service.GenericService;
using IGL.Core.ViewModelEntities.MasterVm;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IGL.UI.Controllers.Master
{
    [Authorize]
    public class MaterialMasterController : Controller
    {
        private readonly IGenericService<MaterialMaster, int> _IMaterialMasterService;
        private readonly IGenericService<UnitMaster, int> _IUnitMasterService;
        private readonly IGenericService<ProductTransactionDetail, int> _IProductTransactionService;
        private readonly IGenericService<RateMaster, int> _IRateMasterService;

        public MaterialMasterController(IGenericService<MaterialMaster, int> _matetialService, IGenericService<UnitMaster, int> _unitMasterService, IGenericService<ProductTransactionDetail, int> productTransactionService, IGenericService<RateMaster, int> rateMasterService)
        {
            _IMaterialMasterService = _matetialService;
            _IUnitMasterService = _unitMasterService;
            _IProductTransactionService = productTransactionService;
            _IRateMasterService = rateMasterService;
        }
        public async Task<IActionResult> Index()
        {
            return await Task.Run(() => View("~/Views/Master/Product/ProductIndex.cshtml"));
        }

        public async Task<IActionResult> GetProductDetails()
        {
            var unitModels = await _IUnitMasterService.GetList(x => x.IsActive == 1);
            var materialModels = await _IMaterialMasterService.GetList(x => x.IsActive == 1);


            var models = (from mt in materialModels
                          join UM in unitModels
                          on mt.UnitId equals UM.Id
                          select new MaterialMasterVm
                          {
                              Id = mt.Id,
                              MaterialName = mt.Name,
                              Code = mt.Code,
                              Unit = UM.Name,
                              PerUnitCost = mt.PerUnitCost,
                              IsPayable = mt.IsPayable == 1 ? "Payable" : "Not Payable",
                              ThresholdValue = mt.ThresholdValue,
                              Quantity = mt.OpeningQuantity,
                              HSNCode = mt.HSNCode,
                              IsUniqe = mt.IsUnique == 1
                          }).ToList();

            return PartialView("~/Views/Master/Product/_ProductList.cshtml", models);

        }

        public async Task<IActionResult> CreateMaterial(int id)
        {
            ViewBag.UnitMaster = await _IUnitMasterService.GetList(x => x.IsActive == 1);
            var materialModel = await _IMaterialMasterService.GetSingle(x => x.Id == id);
            return PartialView("~/Views/Master/Product/_ProductCreate.cshtml", materialModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpSertMaterial(MaterialMaster model)
        {
            if (model.Id == 0)
            {
                var createModel = CommanCRUDHelper.CommanCreateCode(model, 1);
                var createResponse = await _IMaterialMasterService.CreateEntity(createModel);

                var createdPrdctId = (await _IMaterialMasterService.GetList(x => x.IsActive == 1)).Max(x => x.Id);
                var rateMasterResponse = await UpdateRateMaster(createdPrdctId, model.PerUnitCost);

                return Json(ResponseHelper.GetResponseMessage(createResponse));
            }
            else
            {
                var updateModel = CommanCRUDHelper.CommanUpdateCode(model, 1);
                var updateResponse = await _IMaterialMasterService.Update(updateModel);

                var rateMasterResponse = await UpdateRateMaster(model.Id, model.PerUnitCost);

                return Json(ResponseHelper.GetResponseMessage(updateResponse));
            }


        }

        public async Task<IActionResult> AssignProductNumber(int ProductId, int count)
        {
            ViewBag.prodId = ProductId;
            ViewBag.prodCount = count;

            var models = await _IProductTransactionService.GetList(x => x.IsActive == 1 && x.MaterialId == ProductId);

            if (models.Any())
            {
                var itemNumber = new List<string>();
                models.ToList().ForEach(item =>
                {
                    itemNumber.Add(item.ItemNumber);
                });

                ViewBag.ItemNumbes = itemNumber;

            }
            return await Task.Run(() => PartialView("~/Views/Master/Product/UniqueProductNumberPartial.cshtml"));
        }

        [HttpGet]
        public async Task<IActionResult> UpSertProductNumber(int prodId, string[] number)
        {
            var models = await _IProductTransactionService.GetList(x => x.IsActive == 1 && x.MaterialId == prodId);
            models.ToList().ForEach(item =>
            {
                item.IsActive = 0;
                item.IsDeleted = 1;
                item.UpdatedBy = 1;
                item.UpdatedDate = DateTime.Now.Date;
            });
            var response = await _IProductTransactionService.Delete(models.ToArray());
            var prodList = new List<ProductTransactionDetail>();
            for (int i = 0; i < number.Count(); i++)
            {
                ProductTransactionDetail prod = new ProductTransactionDetail()
                {
                    ItemNumber = number[i],
                    MaterialId = prodId,
                    IsActive = 1,
                    IsDeleted = 0,
                    CreatedBy = 1,
                    CreatedDate = DateTime.Now.Date
                };
                prodList.Add(prod);
            }
            var updateResponse = await _IProductTransactionService.Add(prodList.ToArray());
            return Json(ResponseHelper.GetResponseMessage(updateResponse));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _IMaterialMasterService.GetSingle(x => x.Id == id);
            var deleteModel = CommanCRUDHelper.CommanDeleteCode(model, 1);
            await _IMaterialMasterService.CreateNewContext();
            var deleteResponse = await _IMaterialMasterService.Update(deleteModel);
            return Json(ResponseHelper.GetResponseMessage(deleteResponse));

        }

        private async Task<bool> UpdateRateMaster(int prodId, decimal price)
        {
            //Check product exists in RateMaster
            var rateModel = (await _IRateMasterService.GetList(x => x.ProductId == prodId && x.ToDate == null)).FirstOrDefault();

            if (rateModel != null)
            {
                rateModel.ToDate = DateTime.Now.Date;
                var updateResponse = await _IRateMasterService.Update(rateModel);
            }
            RateMaster model = new RateMaster();
            model.ProductId = prodId;
            model.Rate = Convert.ToDecimal(price);
            model.FromDate = DateTime.Now.Date;
            model.ToDate = null;
            var createResponse = await _IRateMasterService.CreateEntity(model);
            return createResponse == Core.Comman.Comman.ResponseMessage.AddedSuccessfully ? true : false;
        }

        public async Task<IActionResult> GetProductPriceDetail(int productId)
        {
            var response = (await _IRateMasterService.GetList(x => x.IsActive == 1 && x.IsDeleted == 0)).ToList();
            return PartialView("~/Views/Master/Product/_ProductRateDetailPartial.cshtml", response.Where(x => x.ProductId == productId).ToList());
        }

        public async Task<IActionResult> IsProductExists(string productName)
        {
            var response = await _IMaterialMasterService.GetSingle(x => x.Name.Trim().ToLower() == productName.Trim().ToLower());
            if (response != null)
                return Json(1);

            return Json(-1);
        }
    }
}

IGL.UI/Views/Master/Product/ProductIndex.cshtml
@{
    ViewData["Title"] = "Product Master";
}

<section class="content-header">
    <h1>
        Product Master
    </h1>
</section>
<section class="content container-fluid">
    <section class="content">
        <div class="row" id="divProductDetail">
        </div>
    </section>
    @await Html.PartialAsync("~/Views/Shared/IGLCommanModal.cshtml")
</section>


<environment include="Production">
    <script src="~/js/Material/Material.js"></script>
</environment>
<environment include="Development">
    <script src="~/js/Material/Material.js"></script>
</environment>

IGL.UI/Views/Master/Product/UniqueProductNumberPartial.cshtml
@{
    var itemNumbers = (List<string>)ViewBag.ItemNumbes;
    var isExists = false;
    if(itemNumbers!=null)
    {
        if (itemNumbers.Count() == (int)ViewBag.prodCount)
            isExists = true;
    }
}

    <form id="form" method="get" data-ajax="true" data-ajax-method="get"
          asp-action="UpSertProductNumber" asp-controller="MaterialMaster" data-ajax-success="productDetail.Fn_Success">
        @if (isExists)
        {
            <div class="row">
                <div class="col-md-12">
                    <input type="hidden" name="prodId" value="@ViewBag.prodId" />
                    @for (var i = 0; i < itemNumbers.Count; i++)
                    {
                        var placeHolder = "Product Number" + i.ToString();
                        <div class="col-md-3">
                            <input type="text" value="@itemNumbers[i]" placeholder="@placeHolder" class="form-control" name="number" />
                        </div>
                    }
                </div>
                <br />
                <br />
                <div class="col-md-12">
                    <input type="submit" class="btn btn-primary pull-right" value="Save" />
                </div>
            </div>
        }
        else
        {
            <div class="row">
                <div class="col-md-12">
                    <input type="hidden" name="prodId" value="@ViewBag.prodId" />
                    @for (var i = 0; i < ViewBag.prodCount; i++)
                    {
                        var placeHolder = "Product Number" + i.ToString();
                        <div class="col-md-3">
                            <input type="text" placeholder="@placeHolder" class="form-control" name="number" />
                        </div>
                    }
                </div>
                <br />
                <br />
                <div class="col-md-12">
                    <input type="submit" class="btn btn-primary pull-right" value="Save" />
                </div>
            </div>
        }

    </form>

IGL.UI/Views/Master/Product/_ProductCreate.cshtml
@model IGL.Core.Entities.Master.MaterialMaster

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<form id="form" method="post" data-ajax="true" data-ajax-method="post"
      asp-action="UpSertMaterial" asp-controller="MaterialMaster" data-ajax-success="productDetail.Fn_Success"
      data-ajax-begin="customAjax.Fn_SubmitBegin(divModalPopUp)" data-ajax-complete="customAjax.Fn_SubmitComplete(divModalPopUp)">
    <div class="row" id="divUnitMasterCreate">
        <div class="col-xs-12">
            <div class="col-md-4 form-group">
                <input type="hidden" asp-for="Id" />
                <label class="control-label"> Name</label>
                <input asp-for="Name" class="form-control" onchange="productDetail.Fn_IsProductExists(this)" />
                <span asp-validation-for="Name"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Code</label>
                <input asp-for="Code" class="form-control" />
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Unit Type</label>
                <select asp-for="UnitId" class="form-control" asp-items="@(new SelectList(ViewBag.UnitMaster,"Id","Name"))">
                    <option value="0">Select</option>
                </select>
            </div>
            <div class="col-md-4 form-group clearB">
                <label class="control-label">Per Unit Cost</label>
                <input asp-for="PerUnitCost" class="form-control" />
                <span asp-validation-for="PerUnitCost"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Is Payable</label>
                <select asp-for="IsPayable" class="form-control">
                    <option value="0">No (IGL Free Product)</option>
                    <option value="1">Yes (Vendor Product)</option>
                </select>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Opening Quantity</label>
                <input asp-for="OpeningQuantity" class="form-control" />
                <span asp-validation-for="OpeningQuantity"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Threshold Quantity</label>
                <input asp-for="ThresholdValue" class="form-control" />
                <span asp-validation-for="ThresholdValue"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Product HSN Code </label>
                <input asp-for="HSNCode" class="form-control" />
                <span asp-validation-for="HSNCode"></span>
            </div>
            <div class="col-md-4 form-group">
                <label class="control-label">Is Each Product Has Unique Number</label>
                <select asp-for="IsUnique" class="form-control">
                    <option value="0">No</option>
                    <option value="1">Yes</option>
                </select>
                <span asp-validation-for="IsUnique"></span>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="col-sm-8">
                <button type="submit" class="btn btn-primary pull-right" value="Save">
                    <i class="fa fa-download"> &nbsp;&nbsp;Save</i>
                </button>
            </div>
            <div class="col-sm-4">
                <button type="reset" class="btn btn-warning" value="reset">
                    <i class="fa fa-refresh">&nbsp;&nbsp;Reset</i>
                </button>
            </div>
        </div>
    </div>
</form>

IGL.UI/Views/Master/Product/_ProductList.cshtml
@model IEnumerable<IGL.Core.ViewModelEntities.MasterVm.MaterialMasterVm>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Product List</h3>

                <button class="btn btn-primary pull-right" onclick="productDetail.Fn_CreateProduct()">
                    <i class="fa fa-plus-circle"> &nbsp; &nbsp; Add &nbsp; &nbsp;</i>
                </button>

            </div>
            <div class="box-body">
                <table id="IGLDataTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Product Code</th>
                            <th>Unit</th>
                            <th>Per Unit Cost</th>
                            <th>Opening Quantity</th>
                            <th>Threshold Value</th>
                            <th>HSN Code</th>
                            <th>Is Payable</th>
                            <th>Is Unique</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var data in Model)
                        {
                            <tr>
                                <td>
                                    @data.MaterialName
                                </td>
                                <td>
                                    @data.Code
                                </td>
                                <th>
                                    @data.Unit
                                </th>
                                <th>
                                    @data.PerUnitCost
                                </th>
                                <th>
                                    @data.Quantity
                                </th>
                                <th>
                                    @data.ThresholdValue
                                </th>
                                <td>
                                    @data.HSNCode
                                </td>
                                <td>
                                    @data.IsPayable
                                </td>
                                <td>
                                    @if (data.IsUniqe)
                                    {
                                       <a class="btn btn-outline-success " onclick="productDetail.Fn_AsssignNumber(@data.Id,@data.Quantity)">
                                           <i class="fa fa-plus-circle">Assign Number</i>
                                       </a>
                                    }
                                    else { 
                                    <span>No</span>
                                    }
                                </td>
                                <td>
                                    <a class="btn btn-outline-danger pull-right" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'  style='color:#DD4B39'></i>" onclick="productDetail.Fn_DeleteProduct(@data.Id, this)">
                                        <i class="fa fa-trash" style="color:#DD4B39"></i>
                                    </a>

                                    <a class="btn btn-outline-success pull-right" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'  style='color:#DD4B39'></i>" onclick="productDetail.Fn_EditProductMaster(@data.Id, this)">
                                        <i class="fa fa-edit" style="color:#3C8DBC"></i>
                                    </a>
                                    <a href="javascript:void(0)" onclick="productDetail.Fn_GetProductCostDetail(@data.Id, '@data.MaterialName')">Cost History</a>
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>

IGL.UI/Views/Master/Product/_ProductRateDetailPartial.cshtml
@model IEnumerable<IGL.Core.Entities.Master.RateMaster>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Product Rate List</h3>
            </div>
            <div class="box-body">
                <table id="IGLDataTable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Price</th>
                            <th>From Date</th>
                            <th>ToDate</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var data in Model)
                        {
                            <tr>
                                <td>
                                    @data.Rate
                                </td>
                                <td>
                                    @data.FromDate.ToShortDateString()
                                </td>
                                <th>
                                    @if (data.ToDate == null)
                                    {
                                        <span style="color:darkblue">
                                            Till Date
                                        </span>
                                    }
                                    else
                                    {
                                        @data.ToDate
                                    }

                                </th>

                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>