IGL.UI/Controllers/UserManagement/RoleAccessController.cs
using IGL.Core.Comman.Helper;
using IGL.Core.Entities.Master;
using IGL.Core.Entities.UserManagement;
using IGL.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace IGL.UI.Controllers.UserManagement
{
    public class RoleAccessController : Controller
    {
        private static string RoleDetails = @"MenuSubMenuAPI/GetRoleDetails";
        private static string RoleAccessDetails = @"MenuSubMenuAPI/GetRoleMenuDetails";
        private static string PostUrl = @"MenuSubMenuAPI/CreateRoleAccess";
        private readonly IConfiguration _configuration;
        private readonly string _apiURL;

        public RoleAccessController(IConfiguration configuration)
        {
            _configuration = configuration;
            _apiURL = _configuration.GetSection("APIURL:BasicUrl").Value;
        }
        public async Task<IActionResult> RoleAccessIndex()
        {

            var responseDetails = await GenericAPIResponse<RoleMaster, string>.GetAPIResponse(_apiURL, RoleDetails);
            if (responseDetails.StatusCode == System.Net.HttpStatusCode.OK)
            {
                ViewBag.RoleMaster = responseDetails.Entities;
            }
            return View("~/Views/RoleAccess/RoleAccessIndex.cshtml");
        }

        public async Task<IActionResult> GetRoleAccessDetails(int roleId)
        {
            ViewBag.roleId = roleId;
            var responseDetails = await GenericAPIResponse<MenuSubMenuModel, string>
                .GetAPIResponse(_apiURL, RoleAccessDetails + "?roleId=" + roleId);

            return PartialView("~/Views/RoleAccess/RoleAccessDetail.cshtml", responseDetails.Entities);
        }

        [HttpPost]
        public async Task<IActionResult> CreateRoleMap(string[] MenuId, int roleId)
        {
            var roleAccessDetails = new List<RoleAccess>();

            GenericResponseModel<string, string> responseModel;

            MenuId.ToList().ForEach(data =>
            {
                var model = new RoleAccess();
                model.IsActive = 1;
                model.IsDeleted = 0;
                model.CreatedBy = 1;
                model.CreatedDate = DateTime.Now;
                model.MenuId = Convert.ToInt32(data);
                model.RoleId = roleId;

                roleAccessDetails.Add(model);
            });

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(_apiURL);

                StringContent content = new StringContent(JsonConvert.SerializeObject(roleAccessDetails),
                    Encoding.UTF8, "application/json");

                using var response = await client.PostAsync(PostUrl, content);
                string apiResponse = await response.Content.ReadAsStringAsync();
                responseModel = JsonConvert.DeserializeObject<GenericResponseModel<string, string>>(apiResponse);
            }
            if (responseModel.StatusCode == System.Net.HttpStatusCode.OK) {
                return Json(responseModel.ResponseMessage);
            }
            return Json(responseModel.ResponseMessage);
        }
    }
}

IGL.UI/Views/RoleAccess/RoleAccessDetail.cshtml
@model IEnumerable<IGL.Core.Entities.Master.MenuSubMenuModel>
@{
    ViewData["Title"] = "Menu Detail";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Employee Details</h3>


            </div>

            <form id="form" method="post" data-ajax="true" data-ajax-method="post"
                  asp-action="CreateRoleMap" asp-controller="RoleAccess" data-ajax-success="Fn_Success"
                  data-ajax-begin="customAjax.Fn_SubmitBegin(divModalPopUp)" data-ajax-complete="customAjax.Fn_SubmitComplete(divModalPopUp)">
                <div class="box-body">
                    <input type="hidden" value="@ViewBag.roleId" name="roleId"/>
                    <table id="IGLDataTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th> Menu</th>
                                <th>Sub Menu</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var data in Model)
                            {
                                <tr>
                                    <td>
                                        @data.Menu
                                    </td>
                                    <td>
                                        @data.SubMenu
                                    </td>
                                    <td>
                                        @if (data.IsMapped == 1)
                                        {


                                            <input type="checkbox" value="@data.Id" checked="checked" name="MenuId" />
                                        }
                                        else
                                        {
                                            <input value="@data.Id" type="checkbox" name="MenuId" />
                                        }

                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>

                    <div class="row">
                        <button class="btn btn-success pull-right">Save</button> 
                    </div>
                </div>
                </form>
        </div>
    </div>
</div>

IGL.UI/Views/RoleAccess/RoleAccessIndex.cshtml
@{
    ViewData["Title"] = "Role Access Detail";
}

<section class="content-header">
    <h1>
        Role Access Detail
    </h1>
</section>
<section class="content container-fluid">
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-4 form-group">
                    <label>Role Details</label>
                    <select class="form-control" id="ddlRole" onchange="GetRoleAccess()" asp-items="@(new SelectList(ViewBag.RoleMaster,"Id","RoleName"))">
                        <option value="0">Select</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row" id="divRoleAccessDetails">
        </div>
    </section>
    @await Html.PartialAsync("~/Views/Shared/IGLCommanModal.cshtml")
</section>


<environment include="Production">

</environment>
<environment include="Development">

</environment>

<script type="text/javascript">
    function GetRoleAccess() {
        $.get("/RoleAccess/GetRoleAccessDetails", { roleId: $("#ddlRole").val() }, function (data) {
            $("#divRoleAccessDetails").html(data);
        })
    }

    function Fn_Success(response) {
        alert(response);
    }
</script>