IGL.UI/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IGL.UI.Controllers
{
    [Authorize]
    public class DashBoardController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Views/DashBoard/DashBoardIndex.cshtml");
        }
    }
}

IGL.UI/Controllers/Inventory/PurchaseOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IGL.Core.Comman.Helper;
using IGL.Core.Entities.Inventory;
using IGL.Core.Entities.Master;
using IGL.Core.Service.GenericService;
using IGL.Core.Service.PurchaseOrder;
using IGL.Core.ViewModelEntities.Inventory;
using IGL.Core.ViewModelEntities.MasterVm;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace IGL.UI.Controllers.Inventory
{
    public class PurchaseOrderController : Controller
    {
        private readonly IGenericService<PurchaseOrder, int> _IPurchaseOrderService;
        private readonly IGenericService<POItem, int> _IPOItemService;
        private readonly IGenericService<VendorMaster, int> _IVendorService;
        private readonly IGenericService<MaterialMaster, int> _IProductService;
        private readonly IGenericService<UnitMaster, int> _IunitMasterService;
        private readonly IGenericService<IGL.Core.Entities.Organization.Organisation, int> _IOrganisationService;
        private readonly IPurchaseOrderService _IPurchaseOrder;

        public PurchaseOrderController(IGenericService<PurchaseOrder, int> purchaseOrderService, 
            IGenericService<POItem, int> poItemService, IGenericService<VendorMaster, int> vendorService, 
            IGenericService<MaterialMaster, int> productService, IGenericService<UnitMaster, int> unitMasterService, 
            IGenericService<IGL.Core.Entities.Organization.Organisation, int> organisationService, IPurchaseOrderService purchaseOrder)
        {
            _IPOItemService = poItemService;
            _IPurchaseOrderService = purchaseOrderService;
            _IVendorService = vendorService;
            _IProductService = productService;
            _IunitMasterService = unitMasterService;
            _IOrganisationService = organisationService;
            _IPurchaseOrder = purchaseOrder;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.PoStatusCount = await _IPurchaseOrder.GetPoStatusCount();
            return View("~/Views/PurchaseOrder/POIndex.cshtml");
        }

        public async Task<IActionResult> CreatePO()
        {
            string poNumber = "PO00" + Convert.ToString(1);
            var poDetails = await _IPurchaseOrderService.GetList(x => x.IsActive == 1);
            if(poDetails.Count()>0)
            {
                poNumber = poNumber + (poDetails.Max(x => x.Id)+1).ToString();
            }
            ViewData["poNumber"] = poNumber;
            var vendorDetails = await _IVendorService.GetList(x => x.IsActive == 1);
            ViewBag.VendorList = vendorDetails;
            return await Task.Run(() => PartialView("~/Views/PurchaseOrder/_CreatePurchaseOrderPartial.cshtml"));
        }

        public async Task<IActionResult> GetPOList(int poStatus)
        {
            /*
             po Status -1 for Po Created
             po status -2 for Approved
             po status -3 for siv created
             po status -4 for siv approved
             */

            var poDetail = await _IPurchaseOrderService.GetList(x => x.IsActive == 1);
            var poItems = await _IPOItemService.GetList(x => x.IsActive == 1);
            var vendorDetails = await _IVendorService.GetList(x => x.IsActive == 1);
            var productDetails = await _IProductService.GetList(x => x.IsActive == 1);

            switch (poStatus)
            {
                case 1:
                    poDetail = poDetail.Where(x => x.POStatus.Trim().ToLower() == "created").ToList();
                    ViewBag.poStatus = "created";
                    break;

                case 2:
                    poDetail = poDetail.Where(x => x.POStatus.Trim().ToLower() == "poapproved").ToList();
                    ViewBag.poStatus = "poapproved";
                    break;

                case 3:
                    poDetail = poDetail.Where(x => x.POStatus.Trim().ToLower() == "sivcreated").ToList();
                    ViewBag.poStatus = "sivcreated";
                    break;

                case 4:
                    poDetail = poDetail.Where(x => x.POStatus.Trim().ToLower() == "sivapproved").ToList();
                    ViewBag.poStatus = "sivapproved";
                    break;

                default:
                    break;
            }



            var models = (from PO in poDetail
                          join VM in vendorDetails
                          on PO.VendorId equals VM.Id
                          join PI in poItems
                          on PO.Id equals PI.PoId
                          join PRD in productDetails
                          on PI.ItemId equals PRD.Id
                          select new PurchaseOrderDetail
                          {
                              PoId = PO.Id,
                              PoNUmber = PO.PONumber,
                              PoDate = PO.PODate,
                              VendorName = VM.VendorName,
                              ItemId = PI.ItemId,
                              ItemName = PRD.Name,
                              Quantity = PI.Quantity,
                              UnitPrice = PRD.PerUnitCost,
                              Amount = PI.Quantity * PRD.PerUnitCost,
                              Remarks = PO.Remarks,
                              POStatus = PO.POStatus
                          }).ToList();

            return PartialView("~/Views/PurchaseOrder/_PurchaseOrderDetails.cshtml", models);

        }

        public async Task<IActionResult> MaterialForPo()
        {
            var unitModels = await _IunitMasterService.GetList(x => x.IsActive == 1);
            var materialModels = await _IProductService.GetList(x => x.IsActive == 1 && x.IsUnique==0);


            var models = (from mt in materialModels
                          join UM in unitModels
                          on mt.UnitId equals UM.Id
                          select new MaterialMasterVm
                          {
                              Id = mt.Id,
                              MaterialName = mt.Name,
                              Code = mt.Code,
                              Unit = UM.Name,
                              PerUnitCost = mt.PerUnitCost,
                              IsPayable = mt.IsPayable == 1 ? "Payable" : "Free (IGL Product)"
                          }).ToList();
            return PartialView("~/Views/PurchaseOrder/_AddMaterialToPOPartial.cshtml", models);
        }

        public async Task<IActionResult> CreatePurchaseOrder(PurchaseOrder model, string[] matId, string[] remarks, string[] qty, string[] unitPrice, int poId)
        {
            //if po already exists then Approve the po
            if ((await _IPurchaseOrderService.GetList(x => x.IsActive == 1 && x.Id== poId)).Count() > 0)
            {
                var poDetail = await _IPurchaseOrderService.GetSingle(x => x.Id == poId);
                poDetail.POStatus = "POApproved";
                await _IPurchaseOrderService.Update(poDetail);
                var poItems = await _IPOItemService.GetList(x => x.PoId == poDetail.Id);

                poItems.ToList().ForEach(item => {
                    item.IsActive = 0;
                    item.IsDeleted = 1;
                    item.UpdatedBy = 1;
                    item.UpdatedDate = DateTime.Now.Date;
                });
                var deletePreviousPoItems = await _IPOItemService.Update(poItems.ToArray());

                List<POItem> tempPOItems = new List<POItem>();

                for (int i = 0; i < matId.Count(); i++)
                {
                    POItem item = new POItem();
                    item.PoId = poDetail.Id;
                    item.ItemId = Convert.ToInt32(matId[i]);
                    item.Quantity = Convert.ToInt32(qty[i]);
                    item.Amount = Convert.ToDecimal(Convert.ToInt32(qty[i]) * Convert.ToDecimal(unitPrice[i]));
                    item.Remarks = remarks[i];
                    item.IsActive = 1;
                    item.IsDeleted = 0;
                    item.CreatedBy = 1;
                    item.CreatedDate = DateTime.Now.Date;
                    tempPOItems.Add(item);
                }

                var itemResponse = await _IPOItemService.Add(tempPOItems.ToArray());
                return Json(ResponseHelper.GetResponseMessage(itemResponse));
            }
            else
            { 
                var createHelper = CommanCRUDHelper.CommanCreateCode(model, 1);
                createHelper.POStatus = "Created";
                var response = await _IPurchaseOrderService.CreateEntity(model);
                var tempPoId = (await _IPurchaseOrderService.GetList(x => x.IsActive == 1)).Max(x => x.Id);

                List<POItem> poItems = new List<POItem>();

                for (int i = 0; i < matId.Count(); i++)
                {
                    POItem item = new POItem();
                    item.PoId = tempPoId;
                    item.ItemId = Convert.ToInt32(matId[i]);
                    item.Quantity = Convert.ToInt32(qty[i]);
                    item.Amount = Convert.ToDecimal(Convert.ToInt32(qty[i]) * Convert.ToDecimal(unitPrice[i]));
                    item.Remarks = remarks[i];
                    item.IsActive = 1;
                    item.IsDeleted = 0;
                    item.CreatedBy = 1;
                    item.CreatedDate = DateTime.Now.Date;
                    poItems.Add(item);
                }

                var itemResponse = await _IPOItemService.Add(poItems.ToArray());
                return Json(ResponseHelper.GetResponseMessage(itemResponse));
            }
           
            }

        public async Task<IActionResult> POPDF(int id)
        {
            List<PurchaseOrderDetail> models = await GetPoDetail(id);
            return PartialView("~/Views/PurchaseOrder/_POPDFPartial.cshtml", models);
        }

IGL.UI/Controllers/MaterialTransaction/MaterialReturnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IGL.Core.Entities.Transaction;
using IGL.Core.Service.GenericService;
using IGL.Core.Service.MaterialDetail;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace IGL.UI.Controllers.MaterialTransaction
{
    public class MaterialReturnController : Controller
    {
        private readonly IProductReturnService _IProductReturnService;
        private readonly IGenericService<MaterialTransction, int> _IMaterialTransactionService;
        public MaterialReturnController(IProductReturnService productReturnService, IGenericService<MaterialTransction, int> materialTransaction)
        {
            _IProductReturnService = productReturnService;
            _IMaterialTransactionService = materialTransaction;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.TransactionDetail = await _IMaterialTransactionService.GetList(x => x.IsActive == 1);
            return View("~/Views/MaterialTransaction/_MaterialReturnIndex.cshtml");
        }

        public async Task<IActionResult> GetProductIssueDetail(int id)
        {
            HttpContext.Session.SetInt32("TransactionId", id);
            var model = await _IProductReturnService.GetMaterialIssueDetail(id);
            return PartialView("~/Views/MaterialTransaction/MaterialReturnPartial.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> ProductReturn(string [] matId,string [] ItemNumber, string [] qty,string slipNumber)
        {
            var models = new List<MaterialReturn>();
            for(int i=0; i<matId.Count();i++)
            {
                var model = new MaterialReturn();
                model.Id = Convert.ToInt32(HttpContext.Session.GetInt32("TransactionId"));
                model.ProductId = Convert.ToInt32(matId[i]);
                model.UniqueItemId =Convert.ToInt32(ItemNumber[i].ToString()??"0");
                model.Quantity = Convert.ToDecimal(qty[i]);
                model.SlipNumber = slipNumber;
                model.TransactionType = "Return";
                model.TransactionDate = DateTime.Now;
                models.Add(model);
            }
            var response = await _IProductReturnService.MaterialReturn(models);
            return Json("");
        }
    }
}

IGL.UI/Views/DashBoard/DashBoardIndex.cshtml
@{
    ViewData["Title"] = "DashBoardIndex";
}

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/drilldown.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<style>
    .highcharts-figure, .highcharts-data-table table {
        min-width: 310px;
        max-width: 800px;
        margin: 1em auto;
    }

    #container {
        height: 400px;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #EBEBEB;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }

    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }

    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }

    .highcharts-data-table td, .highcharts-data-table th, .highcharts-data-table caption {
        padding: 0.5em;
    }

    .highcharts-data-table thead tr, .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }

    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }

</style>

<section class="content container-fluid">
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>ISSUE</h3>

                        <p>Create Material Issue</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a  asp-action="Index" asp-controller="MaterialTransaction" class="small-box-footer">Details <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>RETURN</h3>

                        <p>Create Material Return</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a asp-action="Index" asp-controller="MaterialReturn" class="small-box-footer">Details <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>Purchase</h3>

                        <p>Create Purchase Order</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-cash"></i>
                    </div>
                    <a asp-action="Index" asp-controller="PurchaseOrder" class="small-box-footer">Details <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3>SIV</h3>

                        <p>Store Voucher IGL Product</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a asp-action="Index" asp-controller="SIVIGLProduct" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <div class="row">
            <div class="col-md-6">
                <figure class="highcharts-figure">
                    <div id="container"></div>
                    <p class="highcharts-description">
                        Product Inventory Details.
                    </p>
                </figure>
            </div>
            <div class="col-md-6">
                <figure class="highcharts-figure">
                    <div id="container1"></div>
                    <p class="highcharts-description">
                        Product Issu (/) Return Report
                    </p>
                </figure>
            </div>
        </div>
    </section>
    @await Html.PartialAsync("~/Views/Shared/IGLCommanModal.cshtml")
</section>

<script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Product Inventory Detail'
        },
        subtitle: {
            text: 'IGL Product Details'
        },
        xAxis: {
            categories: [
                'Jan',
                'Feb',
                'Mar',
                'Apr',
                'May',
                'Jun',
                'Jul',
                'Aug',
                'Sep',
                'Oct',
                'Nov',
                'Dec'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Quantity in 100'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Pipe',
            data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

        }, {
            name: 'Regulator',
            data: [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]

        }, {
            name: 'Socket',
            data: [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]

        }, {
            name: 'Meter',
            data: [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1]

        }]
    });

    Highcharts.chart('container1', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Material (Issue/Return) Report'
        },
        subtitle: {
            text: 'IGL Product Details'
        },
        xAxis: {
            categories: [
                'Jan',
                'Feb',
                'Mar',
                'Apr',
                'May',
                'Jun',
                'Jul',
                'Aug',
                'Sep',
                'Oct',
                'Nov',
                'Dec'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Quantity in 100'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Pipe',
            data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

        }, {
            name: 'Regulator',
            data: [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]

        }, {
            name: 'Socket',
            data: [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]

        }, {
            name: 'Meter',
            data: [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1]

        }]
    });
</script>